#!/bin/bash
#PBS -l select=1:ngpus=1
#PBS -P -----
#PBS -l walltime=24:00:00
#PBS -q normal

## Merge standard output and error from PBS script
#PBS -j oe
#PBS -o /home/users/ntu/tianle00/scratch/llmxfm-0.0/chemistry/logs/pbs/qa1.log

# 加载环境模块
module load miniforge3
module load cuda/11.8.0

# 进入工作目录
cd /home/users/ntu/tianle00/scratch/llmxfm-0.0

export HF_HOME=/home/users/ntu/tianle00/scratch/cache
export CONDA_ENVS_PATH=/home/users/ntu/tianle00/scratch/conda/envs
export CONDA_PKGS_DIRS=/home/users/ntu/tianle00/scratch/conda/pkgs

# 激活 Conda 环境
conda activate llmxfm

TSAK_NAME="Property"
# 每个进程负载超时 180 分钟
TIMEOUT_DURATION=72000 # 180 minutes in seconds

MODEL_NAME='/home/users/ntu/tianle00/scratch/cache/hub/models--meta-llama--Meta-Llama-3.1-8B-Instruct/snapshots/0e9e39f249a16976918f6564b8830bc894c89659'

SEEDS=("2021" "7777" "8888" "1111" "2222" "3333" "5555" "101010" "202020" "606060")

SHOTS=(80)

for SEED in "${SEEDS[@]}"; do
    echo "Running for seed: $SEED"

    for SHOT in "${SHOTS[@]}"; do
        echo "Running for shot: $SHOT"

        timeout $TIMEOUT_DURATION python -m chemistry.SC_scripts.QA_run_trainer_icl \
            --experiment_type icl \
            --experiment_name baseline_8B \
            --seed $SEED \
            --task_name $TSAK_NAME \
            --model_name $MODEL_NAME \
            --num_trains 2000 \
            --num_tests 500 \
            --n_representation_shots $SHOT \
            --temperature 1.0 \
        || echo "pca_icl for seed $SEED timed out or failed"


    done

done


TSAK_NAME="Source"

for SEED in "${SEEDS[@]}"; do
    echo "Running for seed: $SEED"

    for SHOT in "${SHOTS[@]}"; do
        echo "Running for shot: $SHOT"

        timeout $TIMEOUT_DURATION python -m chemistry.SC_scripts.QA_run_trainer_icl \
            --experiment_type icl \
            --experiment_name baseline_8B \
            --seed $SEED \
            --task_name $TSAK_NAME \
            --model_name $MODEL_NAME \
            --num_trains 2000 \
            --num_tests 500 \
            --n_representation_shots $SHOT \
            --temperature 1.0 \
        || echo "pca_icl for seed $SEED timed out or failed"


    done

done